### ISSUE TITLE
Git clone creates an uncompatible directory name

### ISSUE THREAD

**Issue by axelpale** [toastdriven/guide-to-testing-in-django#2]
Hay and thanks for the tutorial at http://toastdriven.com/blog/2011/apr/10/guide-to-testing-in-django/ !

My reading experience was stopped by following error at tag 02-first-test:
python manage.py test polls
...
ImportError: No module named guide_to_testing.urls

The command "git clone https://github.com/toastdriven/guide-to-testing-in-django.git" created a directory named guide-to-testing-in-django. After renaming the directory to guide_to_testing, the "python manage.py test polls" worked like expected.

Maybe there is a fix for this? I'm on Ubuntu 10.10 64-bit, running Python 2.6.6, Django 1.3 and Git 1.7.1.

And one other thing being related to the tutorial... My current Git doesn't know command "git co 02-first-test". Only "git checkout 02-first-test" works. Since my git version is default version in Ubuntu repositories, this little problem may affect other people too.

**Comment by okal** [comment]
Same set of problems. Ubuntu 10.10 32-bit, Python 2.6.6, Git 1.7.1 and Django 1.3.1.

**Comment by bernardobarreto** [comment]
since the repository owner didn't accept my pull request, in settings.py just remove the name of the project, let just

> ROOT_URLCONF =  'urls'

**Comment by toastdriven** [comment]
Fixed in SHA: e555952
